name = "Curve25519Dalek"
version = "0.1.0"
keywords = ["formal verification"]
defaultTargets = ["Curve25519Dalek"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.longLine = false
maxRecDepth = 10000

[[require]]
name = "aeneas"
git = "https://github.com/AeneasVerif/aeneas.git"
subDir = "backends/lean"
rev = "b6dfa65d"

[[require]]
name = "PrimeCert"
git = "https://github.com/oliver-butterley/PrimeCert.git"
rev = "ef2148a816e1e8d534c8446dac7f2dafcb4b4888"

[[lean_lib]]
name = "Curve25519Dalek"

[[lean_lib]]
name = "Utils"

[[lean_exe]]
name = "listfuns"
root = "Utils.ListFuns"
supportInterpreter = true

[[lean_exe]]
name = "syncstatus"
root = "Utils.SyncStatus"
supportInterpreter = true
