/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Markus Dablander
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Ristretto.Representation
import Curve25519Dalek.Specs.Backend.Serial.U64.Field.FieldElement51.FromBytes
import Curve25519Dalek.Specs.Ristretto.RistrettoPoint.ElligatorRistrettoFlavor
import Curve25519Dalek.Specs.Ristretto.RistrettoPoint.Add

/-! # Spec theorem for `RistrettoPoint::from_uniform_bytes`

Specification and proof for `RistrettoPoint::from_uniform_bytes`.

This function constructs a uniformly sampled `RistrettoPoint` from 64 bytes of uniform random data
by applying the Ristretto-flavored Elligator map to two field elements generated by two 32-byte
halves and adding the resulting two Ristretto points via elliptic curve addition.

Source: "curve25519-dalek/src/ristretto.rs"
-/

open Aeneas Aeneas.Std Result Aeneas.Std.WP
open curve25519_dalek.math
namespace curve25519_dalek.ristretto.RistrettoPoint

/-
Natural language description:

The Ristretto group is a prime-order group constructed as a quotient of the Edwards curve.
The `from_uniform_bytes` function implements a map from 64 bytes to Ristretto group elements
that ensures a uniform distribution: if the input bytes are uniformly random, the output
Ristretto point is uniformly distributed over the Ristretto group.

The mapping is achieved by:

- Splitting the 64-byte input into two 32-byte halves
- Taking the low 255 bits of each half modulo p and converting to a field element (via `from_bytes`)
- Applying the Ristretto-flavored Elligator map to each field element
  to transform it into a Ristretto point
- Adding the two resulting Ristretto points via elliptic curve addition

Natural language specs:

- The function always succeeds (no panic) for arbitrary 64-byte inputs
- The output is a mathematically valid Ristretto point
  (i.e., an even Edwards point that lies on the curve)
- The output point equals elligator(from_bytes(bytes[0..32])) + elligator(from_bytes(bytes[32..64]))
  in the Ed25519 group, where from_bytes maps 32 bytes to a field element (low 255 bits mod p)
  and elligator is the Ristretto-flavored Elligator map
-/

/-- Returns first 32 bytes of a 64-byte array -/
@[reducible]
def bytes_lower (bytes : Array U8 64#usize) : Array U8 32#usize :=
  ⟨(List.range 32).map (fun i => bytes[i]!), by simp⟩

/-- Returns last 32 bytes of a 64-byte array -/
@[reducible]
def bytes_upper (bytes : Array U8 64#usize) : Array U8 32#usize :=
  ⟨(List.range 32).map (fun i => bytes[32 + i]!), by simp⟩

/-- Maps 32 bytes to a mathematical field element: low 255 bits mod p -/
@[reducible]
def field_from_bytes (b : Array U8 32#usize) : ZMod p :=
  ((U8x32_as_Nat b % 2^255 : ℕ) : ZMod p)

/-- **Spec theorem for `curve25519_dalek::ristretto::RistrettoPoint::from_uniform_bytes`**

The function always succeeds for arbitrary 64-byte inputs. The output is a mathematically valid
Ristretto point equal to
`elligator(from_bytes(bytes[0..32])) + elligator(from_bytes(bytes[32..64]))`. -/
@[progress]
theorem from_uniform_bytes_spec (bytes : Array U8 64#usize) :
    from_uniform_bytes bytes ⦃ (result : RistrettoPoint) =>
      result.IsValid ∧
      result.toPoint =
        (elligator_ristretto_flavor_pure (field_from_bytes (bytes_lower bytes))).val +
        (elligator_ristretto_flavor_pure (field_from_bytes (bytes_upper bytes))).val
      ⦄ := by
  sorry
end curve25519_dalek.ristretto.RistrettoPoint
