/-
Copyright (c) 2026 Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Markus Dablander
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Edwards.EightTorsion
import Curve25519Dalek.Math.Edwards.Representation
import Curve25519Dalek.Specs.Backend.Serial.U64.Field.FieldElement51.FromLimbs

/-! # Spec Theorem for `constants::EIGHT_TORSION`

Specification and proof for the constant `EIGHT_TORSION`.

This constant represents the eight-torsion subgroup E[8] of the Edwards curve,
which consists of eight points P_0, ..., P_7 such that [8]P_i = 0. In the case of Curve25519,
this subgroup is cyclic and is generated by a point P of order eight.

The array is organized such that the i-th element is [i]P, where P is a
generator of order eight. This implies that:

- E[4] (the four-torsion subgroup) corresponds to indices 0, 2, 4, 6
- E[2] (the two-torsion subgroup) corresponds to indices 0, 4

**Source**: curve25519-dalek/src/backend/serial/u64/constants.rs
-/

open Aeneas Aeneas.Std Result Edwards
namespace curve25519_dalek.backend.serial.u64.constants

/-
natural language description:

    • EIGHT_TORSION is a constant array of eight Edwards points representing the
      eight-torsion subgroup E[8] of the Edwards curve, i.e., the set of all points P where [8]P = 0.
    • The subgroup is cyclic, generated by a point P of order eight.
    • The i-th element of the array is [i]P (i times P in the group law).
    • The element at index 0 is the identity point ([0]P = 0).
    • The elements at indices 0,2,4,6 form the four-torsion subgroup E[4].
    • The elements at indices 0,4 form the two-torsion subgroup E[2].

natural language specs:

    • P := EIGHT_TORSION[1] is a valid EdwardsPoint
    • P has order eight (this is equivalent to [4]P ≠ 0 and [8]P = 0, because [8]P = 0 implies that the order of P divides 8)
    • For all i ∈ {0,...,7}: EIGHT_TORSION[i] is a valid EdwardsPoint and EIGHT_TORSION[i] = [i]P
-/

/-- **Spec and proof concerning `backend.serial.u64.constants.EIGHT_TORSION`**:
• P := EIGHT_TORSION[1] is a valid EdwardsPoint
• P has order eight (this is equivalent to [4]P ≠ 0 and [8]P = 0, because [8]P = 0 implies that the order of P divides 8)
• For all i ∈ {0,...,7}: EIGHT_TORSION[i] is a valid EdwardsPoint and EIGHT_TORSION[i] = [i]P
-/
@[progress]
theorem EIGHT_TORSION_spec :
    EIGHT_TORSION ⦃ result =>
      let P := result.val[1]
      P.IsValid ∧ 4 • P.toPoint ≠ 0 ∧ 8 • P.toPoint = 0 ∧
      (∀ (i : Fin 8), result.val[i].IsValid) ∧
      (∀ (i : Fin 8), result.val[i].toPoint = (i : ℕ) • P.toPoint) ⦄ := by
  sorry
end curve25519_dalek.backend.serial.u64.constants
